# Generated by Django 5.2.11 on 2026-04-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_mnsi",
            "0009_alter_abnormalfootappearanceobservations_extra_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abnormalfootappearanceobservations",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Abnormal Foot Appearance Observations",
                "verbose_name_plural": "Abnormal Foot Appearance Observations",
            },
        ),
    ]
